//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVA.Plugin.Time.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVA.Plugin.Time.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3040051	les Escaldes	les Escaldes	Ehskal&apos;des-Ehndzhordani,Escaldes,Escaldes-Engordany,Les Escaldes,esukarudesu=engorudani jiao qu,lai sai si ka er de-en ge er da,Ð­ÑÐºÐ°Ð»ÑŒÐ´ÐµÑ-Ð­Ð½Ð´Ð¶Ð¾Ñ€Ð´Ð°Ð½Ð¸,ã‚¨ã‚¹ã‚«ãƒ«ãƒ‡ã‚¹ï¼ã‚¨ãƒ³ã‚´ãƒ«ãƒ€ãƒ‹æ•™åŒº,èŠå¡žæ–¯å¡çˆ¾å¾·-æ©æˆˆçˆ¾é”,èŠå¡žæ–¯å¡çˆ¾å¾·ï¼æ©æˆˆçˆ¾é”	42.50729	1.53414	P	PPLA	AD		08				15853		1033	Europe/Andorra	2008-10-15
        ///3041563	Andorra la Vella	Andorra la Vella	ALV,Ando-la-Vyey,Andora,Andora la Vela,Andora la Velja,Andora lja Vehl&apos;ja,Andoro Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cities15000 {
            get {
                return ResourceManager.GetString("cities15000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;supplemental&quot;: {
        ///    &quot;version&quot;: {
        ///      &quot;_number&quot;: &quot;$Revision: 13923 $&quot;,
        ///      &quot;_unicodeVersion&quot;: &quot;10.0.0&quot;,
        ///      &quot;_cldrVersion&quot;: &quot;33&quot;
        ///    },
        ///    &quot;windowsZones&quot;: {
        ///      &quot;mapTimezones&quot;: [
        ///        {
        ///          &quot;mapZone&quot;: {
        ///            &quot;_other&quot;: &quot;Afghanistan Standard Time&quot;,
        ///            &quot;_type&quot;: &quot;Asia/Kabul&quot;,
        ///            &quot;_territory&quot;: &quot;001&quot;
        ///          }
        ///        },
        ///        {
        ///          &quot;mapZone&quot;: {
        ///            &quot;_other&quot;: &quot;Afghanistan Standard Time&quot;,
        ///            &quot;_type&quot;: &quot;Asia/Kabul&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string windowsZones {
            get {
                return ResourceManager.GetString("windowsZones", resourceCulture);
            }
        }
    }
}
